### ISSUE TITLE
Marked 2.1.0 breaks linkinator

### ISSUE THREAD

**Issue by MWingbermuhle** [JustinBeckwith/linkinator#315]
Marked version 2.1.0 breaks Linkinator, exiting with error: "Unexpected token ."

```
/tmp/jenkins/workspace/<redacted>/node_modules/marked/src/marked.js:158
          const prevRenderer = extensions.renderers?.[ext.name];
                                                    ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/jenkins/workspace/<redacted>/node_modules/linkinator/build/src/server.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Work-around: Putting Marked version to '2.0.7' in your own package.json does make it work

**Comment by MWingbermuhle** [comment]
Resolved by Marked release 2.1.1
