### ISSUE TITLE
Frequent EADDRINUSE

### ISSUE THREAD

**Issue by rrthomas** [JustinBeckwith/linkinator#319]
I often get errors like this:

```
Error: listen EADDRINUSE: address already in use :::5269
      at Server.setupListenHandle [as _listen2] (net.js:1320:16)
      at listenInCluster (net.js:1368:12)
      at Server.listen (net.js:1454:7)
      at /home/rrt/Software/ruth/node_modules/linkinator/src/server.ts:36:8
      at new Promise (<anonymous>)
      at Object.startWebServer (node_modules/linkinator/src/server.ts:33:10)
      at LinkChecker.check (node_modules/linkinator/src/index.ts:84:22)
      at Object.check (node_modules/linkinator/src/index.ts:416:19)
```

Indeed, the port is already in use! I guess that Linkinator is using a random port; presumably it should retry if it guesses one that's already being used?

Thanks for Linkinator!

**Comment by JustinBeckwith** [comment]
I think you addressed this in #328 which is now landed!
