### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by XhmikosR** [JustinBeckwith/linkinator#60]
It seems currently on Windows, there are 11 failing tests.

There should be test on Windows.

```
> linkinator@0.0.0 pretest C:\Users\xmr\Desktop\linkinator
> npm run compile


> linkinator@0.0.0 compile C:\Users\xmr\Desktop\linkinator
> tsc -p .


> linkinator@0.0.0 test C:\Users\xmr\Desktop\linkinator
> nyc mocha build/test



  linkinator
    1) should perform a basic shallow scan
    2) should only try a link once
    3) should skip links if asked nicely
    4) should report broken links
    5) should handle relative links
    √ should handle fetch exceptions
    6) should skip mailto: links
    √ should report malformed links as broken
    7) should detect broken image links
    8) should perform a recursive scan
    9) should not recurse non-html files
    10) should not recurse by default
    11) should retry with a GET after a HEAD


  2 passing (126ms)
  11 failing

  1) linkinator
       should perform a basic shallow scan:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(results.passed)

      + expected - actual

      -false
      +true

      at Context.it (test\test.ts:21:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) linkinator
       should only try a link once:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(results.passed)

      + expected - actual

      -false
      +true

      at Context.it (test\test.ts:30:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  3) linkinator
       should skip links if asked nicely:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(results.passed)

      + expected - actual

      -false
      +true

      at Context.it (test\test.ts:40:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  4) linkinator
       should report broken links:

      AssertionError [ERR_ASSERTION]: Mocks not yet satisfied:
HEAD http://fake.local:80/
      + expected - actual

      -false
      +true

      at Scope.done (node_modules\nock\lib\scope.js:155:10)
      at Context.it (test\test.ts:57:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  5) linkinator
       should handle relative links:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(results.passed)

      + expected - actual

      -false
      +true

      at Context.it (test\test.ts:65:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  6) linkinator
       should skip mailto: links:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(results.passed)

      + expected - actual

      -false
      +true

      at Context.it (test\test.ts:83:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  7) linkinator
       should detect broken image links:

      AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 1
+ 2
      + expected - actual

      -1
      +2

      at Context.it (test\test.ts:101:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  8) linkinator
       should perform a recursive scan:

      AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 1
+ 5
      + expected - actual

      -1
      +5

      at Context.it (test\test.ts:121:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  9) linkinator
       should not recurse non-html files:

      AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 1
+ 2
      + expected - actual

      -1
      +2

      at Context.it (test\test.ts:130:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  10) linkinator
       should not recurse by default:

      AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 1
+ 2
      + expected - actual

      -1
      +2

      at Context.it (test\test.ts:135:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  11) linkinator
       should retry with a GET after a HEAD:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(results.passed)

      + expected - actual

      -false
      +true

      at Context.it (test\test.ts:148:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)



----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
npm ERR! Test failed.  See above for more details.

```

**Comment by JustinBeckwith** [comment]
Thanks for the heads up!  Can you share what version of Nodejs you're running?

**Comment by XhmikosR** [comment]
Node.js 10.15.3 on Windows 10 x64.

I had a quick look at Cirrus CI and it seems they support Windows. I'd go with 18.03 or 18.09, I'm just not too familiar with Cirrus CI to submit a PR myself.

**Comment by XhmikosR** [comment]
BTW I hope the fix for the Windows fixes does fix the issue I'm having that I reported on https://github.com/JustinBeckwith/linkinator/pull/58#issuecomment-489470269.
